; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
platform = espressif32@6.7.0
board = arduino_nano_esp32
framework = arduino

upload_protocol = dfu
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_unflags = -flto
build_flags =
  -fno-lto
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_NANO_ESP32_USB_ON_BOOT=1
